######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 21 19:40:58 2012
######################################################################

TEMPLATE = app
TARGET = wordCount
DEPENDPATH += .
INCLUDEPATH += ../src

# Input
SOURCES += main.cpp ../src/Dictionary.cpp
