######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 21 19:32:46 2012
######################################################################

TEMPLATE = app
TARGET = spellCheck
DEPENDPATH += .
INCLUDEPATH += ../src

# Input
SOURCES += main.cpp ../src/Dictionary.cpp
